ci:
  skip: [mypy, pytest]
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
    - id: pyupgrade
      args: [--py38-plus]

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [-C]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-future-annotations,
            flake8-bugbear,
            flake8-comprehensions,
          ]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.1
    hooks:
      - id: pylint
        args: ["--disable=import-error"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        require_serial: true

      - id: pytest
        name: pytest
        entry: pytest --cov=src/torch_nested --cov-report term-missing --durations=0
        language: python
        types: [python]
        always_run: true
        pass_filenames: false
        verbose: true
